### ISSUE TITLE
Intermediate node connectivity issue for JP node.

### ISSUE THREAD

**Issue by Noir16** [safing/spn#183]
### What happened?
If fixed as a Japan exit node or intermediate node, it will not connect to nodes in other countries except for the same Japan node.

### What did you expect to happen?
1. Designate a relatively close node as an intermediate node.
2. In privacy focus mode, intermediate nodes except the exit node will behave randomly.

### How did you reproduce it?
Set the exit node option or intermediate node to JP.

### Additional information
**Debug-Info**: https://support.safing.io/privatebin/?53472d351fca2133#GseAvyEVKvyoqvHbUxMyVgzyJxSagdr4P9i7TPWGNLRD

**Comment by dhaavi** [comment]
I'm not sure I understand exactly what you mean. Please provide an example.

**Comment by Noir16** [comment]
![1](https://github.com/safing/spn/assets/112380807/4c1cd8fe-7bb7-4e4d-901e-5c798cc06dd8)
![2](https://github.com/safing/spn/assets/112380807/cba36135-5d48-4e62-85e5-9823cac795dd)
The Home Node or Transit Node will be pinned as shown below.
I live in an Asian country, and I think the node optimization is still a bit lacking for use in Asian countries.
For example, it would be ideal to connect through an Indonesia or an India or Singapore server, but in practice, nodes in Japan often only connect to each other.

**Comment by dhaavi** [comment]
Thanks, I now understand better.

The reason for this is that routes are (also) optimized based on speed.
In the case of the eastern Asia, connectivity between servers isn't all that great, so two servers next to each other will most of the times be the cheapest option Portmaster can calculate.

One way we can improve this, of course, is to spin up more nodes there. However, we are having difficulties finding good providers in that region that don't charge horrendous amounts for traffic. If you know any good providers, please do let us know!

We are thinking about adding a settings where users can choose to prioritize either speed, or proximity of the server to the destination (slower, also because more hops will often be involved.)
I think this could solve your issue on the client side. What do you think of this?

**Comment by Noir16** [comment]
For now, I think it would be nice to have the ability to prioritize either speed or proximity.
So what does the Privacy focus do? I thought it was the same as the above features.

**Comment by dhaavi** [comment]
Great! We might also merge it into the routing algorithm setting - we have to think this through first. It might get too complicated to understand when these are separated.
They control different aspects of the same thing, afterall.
